# Generated by Django 3.0.5 on 2021-10-26 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/discussion/%Y/%m/%d/')),
                ('category', models.CharField(blank=True, choices=[('FinTech', 'FinTech'), ('HealthTech', 'HealthTech'), ('InsuranceTech', 'InsuranceTech'), ('AutomobileTech', 'AutomobileTech'), ('Internet', 'Internet'), ('EduTech', 'EduTech'), ('Gaming', 'Gaming'), ('Wearables', 'Wearables'), ('OpenSource', 'OpenSource'), ('Others', 'Others')], default='Others', max_length=25)),
                ('tags', models.CharField(blank=True, help_text='Separate tags with comma', max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forums.Discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
